### PR TITLE
Add compatibility with spatie/crawler 8.0

### PR DESCRIPTION
**Pull request by thoasty-dev**
```
- spatie/laravel-sitemap[6.2.4, ..., 6.3.1] require spatie/crawler ^7.0 -> found spatie/crawler[7.0.0, ..., 7.1.3] but it conflicts with your root composer.json require (^8.0).```

### CODE REVIEW

**Comment by mikkpokk** [comment]
@freekmurze Would love to see that release. Currently I cannot use the package in my project, which already uses crawler 8.0.1 😞

**Comment by thoasty-dev** [comment]
If you really need to, you can use the patch like this with composer in the meantime:

```
{
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/thoasty-dev/laravel-sitemap.git"
        }
    ],


    "require": {
        "spatie/laravel-sitemap": "dev-patch-1"
    },
}
```

**Comment by freekmurze** [comment]
Seems like the tests are failing, could you take a look?

**Comment by thoasty-dev** [comment]
We need to remove ^7.0 from the dependencies, but this will be a breaking change.

**Comment by freekmurze** [comment]
I've handled this myself. The latest versions now supports crawler v8.

**Pull request closed without merging**
