### PR TITLE
Customize the presentation for <lastmod> tag

### PR DESCRIPTION
**Pull request by Lloople**
Be able to format the datetime of the tag <lastmod> through the configuration file.

### CODE REVIEW

**Comment by freekmurze** [comment]
Is there any reason why this should be customizable?

**Comment by Lloople** [comment]
I checked the sitemaps generated by my team over the last years and they always used another format. Maybe it depends on the country? They are showing lastmod in Y-m-d

**Comment by freekmurze** [comment]
Unless there's a test that proves that format should be configurable I'm not going to merge this change in.

**Comment by SurfJunky** [comment]
i knew its very old topic, just started to use this package
if someone else still looking for changing the format of the lastmod date here is the steps

**Step 1**
Find > url.blade.php
in [C:\your-project\vendor\spatie\laravel-sitemap\resources\views](url)
> if you published the files you don't need to go this path

**Step 2**
Open > url.blade.php with your favor-editor
Find this code
`<lastmod>{{ $tag->lastModificationDate->format(DateTime::ATOM) }}</lastmod>`
Replace with
` <lastmod>{{ $tag->lastModificationDate->format('Y-m-d') }}</lastmod>`

Good luck.

**Pull request closed without merging**
