### PR TITLE
Typos and styling 

### PR DESCRIPTION
**Pull request by juukie**

### CODE REVIEW

**Comment by freekmurze** [comment]
Thanks again Jürgen. Like always: much appreciated.

See you tomorrow?

**Comment by juukie** [comment]
For sure! I've got some interesting idea's for this package we can talk about too. 👍

**Comment by freekmurze** [comment]
Suggestions are always welcome! I'll wait a little bit to tag 1.0.0 so we can do still do some breaking changes if needed.

**Comment by juukie** [comment]
Great!

**Pull request merged**
