### PR TITLE
add writeToDisk() logic

### LINKED ISSUE #282: Write sitemap to storage disk instead of absolute path
It would make things a lot easier if it would be possible to write sitemaps to a storage disk + filepath instead of a single absolute path. The most common would be the `public` storage I think.

### PR DESCRIPTION
**Pull request by Gummibeer**
closes #282 

Should I add it to the docs? Or should it stay undocumented?

### CODE REVIEW

**Comment by freekmurze** [comment]
Thanks, could looks good.

> Should I add it to the docs?

Yup! Could you also update the readme in this PR.

**Comment by Gummibeer** [comment]
@freekmurze have added an example to the readme with, I think, the most common use-case.

**Comment by freekmurze** [comment]
Thanks!

**Comment by pierrocknroll** [comment]
@freekmurze can you please make a release ? thanks !

**Comment by freekmurze** [comment]
Whoops, forgot that. Done!

**Comment by Gummibeer** [comment]
https://github.com/spatie/laravel-sitemap/releases/tag/5.6.0 🎉

**Pull request merged**
