### PR TITLE
Add the possibility to add images to sitemaps

### PR DESCRIPTION
**Pull request by madman-81**
Add the possibility to add images to sitemaps. 

See also https://developers.google.com/search/docs/advanced/sitemaps/image-sitemaps

This solves #447

### CODE REVIEW

**Comment by madman-81** [comment]
@freekmurze You mean in the Readme.md?

**Comment by freekmurze** [comment]
Yes

**Comment by madman-81** [comment]
Done 👍

**Comment by freekmurze** [comment]
Thanks!

**Pull request merged**
