### PR TITLE
⚡ Fix memory leak

### PR DESCRIPTION
**Pull request by Prysis**
More info:
https://github.com/spatie/laravel-sitemap/issues/394

### CODE REVIEW

**Comment by freekmurze** [comment]
Thanks for your work on this.

I'm thinking I don't want to take on this extra logic. If there is a memory leak in Blade, it should be solved there.

**Comment by Prysis** [comment]
Your right Blade should not cache render result in memory.
But I think at first place Blade do not made for generating very large files like sitemap
They are are bad in performance, That's why they should compile to php file and Laravel don't use them directly
But this code use them directly on sitemap files which usually very big
In my case (~40,000 link) it use more then 7GB ram and made server down

**Comment by freekmurze** [comment]
I'm ok with changing from Blade to something else, but the current implementation is not maintainable imho 

I'd rather have a renderer like the one is [spatie/ignition](https://github.com/spatie/ignition/blob/main/src/ErrorPage/Renderer.php#L7) with a view file. Test should also be added to make sure that it works correctly.

**Comment by Prysis** [comment]
I'm not sure using include and ob_start / ob_get_clean has what side effects (in this case).
but the codes get cleaner.

**Comment by freekmurze** [comment]
> but the codes get cleaner.

I'm all for clean code 🙂

**Comment by Prysis** [comment]
It's will be like this

image

**Pull request closed without merging**
