### PR TITLE
added sitemap namespace configuration

### PR DESCRIPTION
**Pull request by hsntngr**
This PR allow devs to add custom namespaces on their sitemaps

I was out of network for a while and I couldn't update my pr before

### CODE REVIEW

**Comment by freekmurze** [comment]
When would you want to change the namespace?

**Comment by hsntngr** [comment]
@freekmurze on multilingual sitemaps which each url has alternate uri (number of supported languages)

**Comment by freekmurze** [comment]
What does the namespace look like for those sitemaps?

**Comment by hsntngr** [comment]
I made pr before but, I weren't able to follow it for a while 

https://github.com/spatie/laravel-sitemap/pull/236

To solve my problem I used my own fork and I hope those changes may help whom encounter with the same problem like me

**Comment by hsntngr** [comment]
@freekmurze google shows some errors when you add sitemap on search console

**Comment by freekmurze** [comment]
Could you make sure all tests run correctly? You can regenerate snapshots with `phpunit -d --update-snapshots`

**Comment by hsntngr** [comment]
@freekmurze it seems ok

**Pull request closed without merging**
