### PR TITLE
Fix custom profiles (issue #103)

### LINKED ISSUE #103: Exception with the new CrawlSubdomains profile
Hi,

I was trying out the new CrawlSubdomains profile of the spatie/crawler package. But when I run sitemap:generate, I get this error: `Type error: Argument 1 passed to Spatie\Crawler\CrawlSubdomains::__construct() must be of the type string, object given, called in /.../vendor/spatie/laravel-sitemap/src/SitemapGenerator.php on line 123`.

This is in my config: `'crawl_profile' => CrawlSubdomains::class,`

Switching back to the default Profile will fix this error message.

### PR DESCRIPTION
**Pull request by BrentRobert**
This fixes #103 that all the profiles can be used.

### CODE REVIEW

**Comment by AlexVanderbist** [comment]
Looks good! Added some commits to your PR to allow a bit more flexibility for custom `shouldCrawl` callbacks and custom crawl profiles. 

We should probably define a better `CrawlProfile` interface in the next major version of spatie/crawler or even an abstract `CrawlProfile` that can be extended and includes a way to set the base url and a custom `shouldCrawl` callback on all crawl profiles.

**Comment by AlexVanderbist** [comment]
Created an issue about the `CrawlProfile` interface here: https://github.com/spatie/crawler/issues/82

**Comment by freekmurze** [comment]
Tests seem to fail for this one

**Comment by AlexVanderbist** [comment]
Tests were failing due to a bug in phpunit (fixed in v6.4.1). Tests fixed on master as well now!

**Pull request merged**
